//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Definition.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Definition.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file format is not supported for now.
        /// </summary>
        public static string FileFormatNotSupported {
            get {
                return ResourceManager.GetString("FileFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File includes invalid data.
        /// </summary>
        public static string FileIncludesInvalidData {
            get {
                return ResourceManager.GetString("FileIncludesInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File includes invalid instruction: {0}.
        /// </summary>
        public static string FileIncludesInvalidInstruction {
            get {
                return ResourceManager.GetString("FileIncludesInvalidInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File includes invalid number: {0}.
        /// </summary>
        public static string FileIncludesInvalidNumber {
            get {
                return ResourceManager.GetString("FileIncludesInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty.
        /// </summary>
        public static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is null.
        /// </summary>
        public static string FileIsNull {
            get {
                return ResourceManager.GetString("FileIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is invalid.
        /// </summary>
        public static string FileNameIsInvalid {
            get {
                return ResourceManager.GetString("FileNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect operation found.
        /// </summary>
        public static string IncorrectOperation {
            get {
                return ResourceManager.GetString("IncorrectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid divided input found.
        /// </summary>
        public static string InvalidDividedInput {
            get {
                return ResourceManager.GetString("InvalidDividedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file includes invalid number of apply instraction.
        /// </summary>
        public static string InvalidNumberOfApply {
            get {
                return ResourceManager.GetString("InvalidNumberOfApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last line does not include apply instraction.
        /// </summary>
        public static string LastLineNotApply {
            get {
                return ResourceManager.GetString("LastLineNotApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no file.
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, but don&apos;t worry our team already started working on it..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
    }
}
